//import { Inter } from "next/font/google";
import { Archivo_Black } from "next/font/google";
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });
const archivoBlack = Archivo_Black({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Growth Gen AI | Business growth with automation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archivoBlack.className}>{children}</body>
    </html>
  );
}
